# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
author: Chenyan Xiong and Laura Dietz # jekyll-seo-tag > real name
social: # jekyll-seo-tag > social overrides
  name: Chenyan Xiong # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://www.cs.cmu.edu/~cx

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: USA/ESR # Timezone for blog posts and alike

# 5. Collections
collections:
  news:
    title: news # Needed for Siteleaf
    output: true
    description: "Latest News" # The post list page content
    feature_text: |
<<<<<<< HEAD
      Latest News
#    feature_image: "https://unsplash.it/1300/400?image=1067"
=======
      Welcome to the blog
    feature_image: "https://picsum.photos/2560/600?image=866"
>>>>>>> daviddarnes/master

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
<<<<<<< HEAD
      layout: home # Default layout
      image: "/assets/placeholder-social.png" # Default image for sharing
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post # Default layout
      image: "/assets/placeholder-social.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
title: "KG4IR" # Site name or title, also used in jekyll-seo-tag
logo: "/pic/sigir_title.png" # Site logo, also used in jekyll-seo-tag
description: "The first workshop of Knowledge Graph and Semantics for Text Analysis and Retrieval." # Site description and default description, also used in jekyll-seo-tag
url: "https://kg4ir.github.io" # Site url, also used in jekyll-seo-tag
# repo: "https://kg4ir.github.io/"
email: "cx@cs.cmu.edu"
# disqus: "alembic-1"
# avatarurl: "https://kg4ir.github.io/" # Uses avatars for favicons to get multple sites, eg Gravatar, Twitter, GitHub
=======
      image: "/assets/default-social-image.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "Alembic" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logo.svg" # Site logo, also used in jekyll-seo-tag
description: "Alembic is a starting point for Jekyll projects. Rather than starting from scratch, this boilerplate is designed to get the ball rolling immediately" # Site description and default description, also used in jekyll-seo-tag
url: "https://alembic.darn.es" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/daviddarnes/alembic"
email: "me@daviddarnes.com"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
avatarurl: "https://www.gravatar.com/avatar/6c0377abcf4da91cdd35dea4554b2a4c" # Uses avatars for favicons to get multple sites, eg Gravatar, Twitter, GitHub
# google_analytics: ''
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference
>>>>>>> daviddarnes/master

# 8. Site navigation
navigation_header:
  Home: /
#  Call for Participation: /cfp/
  Submit and Dates: /submit/
#  Important Dates: /dates/
  Organization: /organization/
  Previous: /previous/

navigation_footer:
  Created by Chenyan Xiong: http://www.cs.cmu.edu/~cx/

<<<<<<< HEAD
social_links:
#  Twitter: https://twitter.com/DavidDarnes
#  LinkedIn: https://www.linkedin.com/in/daviddarnes
#  Google+: https://plus.google.com/+DavidDarnes
#  GitHub: https://github.com/daviddarnes
#  link: https://darn.es

# sharing_links:
#  Twitter: "#1DA1F2"
#  facebook: "#3B5998"
#  Google+: "#DC4E41"
#  Pinterest: "#BD081C"
#  LinkedIn: "#0077B5"
#  tumblr: "#36465D"
#  Reddit: "#FF4500"
#  Hacker News: "#ff6600"
#  Designer News: "#2D72D9"
#  Email: ""
=======
social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/DavidDarnes
  LinkedIn: https://www.linkedin.com/in/daviddarnes
  Google+: https://plus.google.com/+DavidDarnes
  GitHub: https://github.com/daviddarnes
  link: https://darn.es
  RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Google+: "#DC4E41"
  # Pinterest: "#BD081C"
  # LinkedIn: "#0077B5"
  # tumblr: "#36465D"
  # Reddit: "#FF4500"
  # Hacker News: "#ff6600"
  # Designer News: "#2D72D9"
  # Email: ""
>>>>>>> daviddarnes/master
